-- MySQL Script generated by MySQL Workbench
-- vie 14 oct 2022 09:42:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Escuela` ;
USE `Escuela` ;

-- -----------------------------------------------------
-- Table `Escuela`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Alumnos` (
  `idAlumnos` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idAlumnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Alumnos` (
  `idAlumnos` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idAlumnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Cursos` (
  `idCursos` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idCursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Escuela`.`Alumnos_has_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Escuela`.`Alumnos_has_Cursos` (
  `Alumnos_idAlumnos` INT NOT NULL,
  `Cursos_idCursos` INT NOT NULL,
  PRIMARY KEY (`Alumnos_idAlumnos`, `Cursos_idCursos`),
  INDEX `fk_Alumnos_has_Cursos_Cursos1_idx` (`Cursos_idCursos` ASC) VISIBLE,
  INDEX `fk_Alumnos_has_Cursos_Alumnos_idx` (`Alumnos_idAlumnos` ASC) VISIBLE,
  CONSTRAINT `fk_Alumnos_has_Cursos_Alumnos`
    FOREIGN KEY (`Alumnos_idAlumnos`)
    REFERENCES `Escuela`.`Alumnos` (`idAlumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumnos_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `Escuela`.`Cursos` (`idCursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
